from functools import cached_property

from django.conf import settings
from django.db import models
import uuid


class Line(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)

    previous = models.ForeignKey('self', blank=True, null=True, related_name='next', on_delete=models.PROTECT)
    text = models.TextField()
    is_last = models.BooleanField(default=False)

    is_manual = models.BooleanField(default=False)
    # the line is manually written by the user or generated by AI

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True, null=True,
        on_delete=models.SET_NULL,
        related_name="lines",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    liked_by = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="liked_lines",
        blank=True,
    )


class Story(models.Model):
    uuid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)

    title = models.TextField(blank=True, null=True)
    tagline = models.TextField(blank=True, null=True)

    last_line = models.ForeignKey(Line, on_delete=models.PROTECT, null=True, blank=True)
    # the final line of the story

    liked_by = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        related_name="liked_stories",
        blank=True,
    )

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "stories"

    def __str__(self):
        return self.title

    def author(self):
        return self.last_line.author

    @cached_property
    def get_lines(self):
        """
        Returns the lines of the story
        """
        return []

