# Generated by Django 5.0.2 on 2024-04-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercredit",
            name="available",
            field=models.IntegerField(default=3),
        ),
    ]
