# Generated by Django 5.0.2 on 2024-04-11 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_alter_usercredit_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercredit", name="used", field=models.IntegerField(default=0),
        ),
    ]
