# Generated by Django 5.0.2 on 2024-04-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_usercredit_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercredit",
            name="available",
            field=models.IntegerField(default=10),
        ),
    ]
