# Generated by Django 5.2.3 on 2025-06-19 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="audio_file",
        ),
        migrations.RemoveField(
            model_name="story",
            name="cover_image",
        ),
        migrations.RemoveField(
            model_name="story",
            name="language",
        ),
        migrations.RemoveField(
            model_name="story",
            name="target_age",
        ),
        migrations.RemoveField(
            model_name="story",
            name="text",
        ),
        migrations.RemoveField(
            model_name="story",
            name="themes",
        ),
        migrations.RemoveField(
            model_name="story",
            name="title",
        ),
        migrations.AddField(
            model_name="story",
            name="original_language",
            field=models.CharField(default="en", max_length=10),
        ),
        migrations.AddField(
            model_name="story",
            name="parameters",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="story",
            name="prompt",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="StoryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="images/")),
                ("cover", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="stories.story",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                ("is_auto", models.BooleanField(default=True)),
                ("title", models.CharField(max_length=255)),
                ("text", models.TextField()),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "unique_together": {("story", "language")},
            },
        ),
        migrations.CreateModel(
            name="StoryAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mp3", models.FileField(blank=True, upload_to="audio/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audio",
                        to="stories.storytranslation",
                    ),
                ),
            ],
        ),
    ]
