# Generated by Django 5.2.3 on 2025-06-20 09:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="story",
            options={"verbose_name_plural": "stories"},
        ),
        migrations.AddField(
            model_name="story",
            name="liked_by",
            field=models.ManyToManyField(
                blank=True, related_name="liked_stories", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
