# Generated by Django 5.2.3 on 2025-06-27 07:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0004_playlist_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="uuid",
            field=models.UUIDField(null=True, editable=False),
        ),
    ]
