# Generated by Django 5.2.3 on 2025-07-01 06:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0007_make_uuid_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyaudio",
            name="prompt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="storyimage",
            name="prompt",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="storytext",
            name="prompt",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="story",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
