# Generated by Django 5.2.3 on 2025-12-16 06:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_storyaudio_prompt_storyimage_prompt_storytext_prompt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storyaudio',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storyaudio',
            name='story',
        ),
        migrations.RemoveField(
            model_name='storyimage',
            name='story',
        ),
        migrations.AlterUniqueTogether(
            name='storytext',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='storytext',
            name='story',
        ),
        migrations.RemoveField(
            model_name='story',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='story',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='story',
            name='original_language',
        ),
        migrations.RemoveField(
            model_name='story',
            name='parameters',
        ),
        migrations.RemoveField(
            model_name='story',
            name='prompt',
        ),
        migrations.RemoveField(
            model_name='story',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='story',
            name='forked_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='stories.story'),
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.TextField(default='Untitled Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField()),
                ('is_last', models.BooleanField(default=False)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to=settings.AUTH_USER_MODEL)),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_lines', to=settings.AUTH_USER_MODEL)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next', to='stories.line')),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stories.line'),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
        migrations.DeleteModel(
            name='StoryAudio',
        ),
        migrations.DeleteModel(
            name='StoryImage',
        ),
        migrations.DeleteModel(
            name='StoryText',
        ),
    ]
