# Generated by Django 5.2.3 on 2025-12-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_alter_storyaudio_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='forked_from',
        ),
    ]
