# Generated by Django 5.2.3 on 2025-12-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_remove_story_forked_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='end',
            new_name='last_line',
        ),
        migrations.RemoveField(
            model_name='story',
            name='author',
        ),
        migrations.AddField(
            model_name='story',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
